# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000 # 500000 for 6h_vs_8z

runner: "parallel"
batch_size_run: 4 # batch_size_run=4, buffer_size = 2500, batch_size=64  for 3s5z_vs_3s6z
buffer_size: 5000 
batch_size: 128
optimizer: 'adam'

t_max: 10050000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
n_unit_types: 3
mac: "Kalei_type_n_mac"
agent: "Kalei_type_n_rnn_1R3"
agent_output_type: q

learner: "Kalei_nq_learner"
mixer: "qmix"
mixing_embed_dim: 32
hypernet_embed: 64
lr: 0.001 # Learning rate for agents
td_lambda: 0.6 # 0.3 for 6h_vs_8z
optimizer: 'adam'
q_lambda: False

Kalei_args:
  deque_len: 100
  div_coef: 5.0
  threshold_init_scale: 5.0
  threshold_init_bias: 5.0
  threshold_reset_scale: 5.0
  threshold_reset_bias: 5.0
  reset_interval: 1_000_000
  reset_ratio: 0.2
  sparsity_layer_weights:
    - 1.0
    - 2.0 
    - 4.0 
    - 8.0 

name: "Kalei_qmix_rnn_1R3"

