# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval_or_tau: 200


obs_agent_id: True
obs_last_action: False
obs_individual_obs: False


# use the Q_Learner to train
standardise_returns: False
standardise_rewards: True

agent_output_type: "q"
agent: "Kalei_rnn_1R3"
mac: "Kalei_mac"
learner: "Kalei_q_Learner"
double_q: True
mixer: "qmix"
use_rnn: True
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

name: "Kalei_qmix_rnn_1R3"

Kalei_args:
  deque_len: 100
  div_coef: 0.5
  threshold_init_scale: 5.0
  threshold_init_bias: 5.0
  threshold_reset_scale: 5.0
  threshold_reset_bias: 5.0
  reset_interval: 200_000
  reset_ratio: 0.1
  sparsity_layer_weights:
    - 1.0
    - 2.0 
    - 4.0 
    - 8.0 
